[package]
name = "counter"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
sauron = "0.61.0"
js-sys = "0.3"
web-sys = { version = "0.3", features = ["HtmlImageElement", "Document", "Window", "History", "Location", "PopStateEvent", "EventTarget"] }
